namespace ManufacturingAdvanced.Core;

using ManufacturingAdvanced.Preflight;
using ManufacturingAdvanced.RefreshGuard;
using ManufacturingAdvanced.WIPControl;

permissionset 85000 "MFG Objects"
{
    Assignable = false;
    Caption = 'Manufacturing Advanced - Objects', Locked = true;

    Permissions =
        table "MFG Setup" = X,
        table "MFG Setup Step" = X,
        table "MFG Demo Data" = X,
        page "MFG Setup" = X,
        page "MFG Setup Hub" = X,
        page "MFG Feature Setup Wizard" = X,
        codeunit "MFG Setup Logic" = X,
        codeunit "MFG Feature Mgt." = X,
        codeunit "MFG Guided Setup" = X,
        codeunit "MFG Install" = X,
        codeunit "MFG Upgrade" = X,
        codeunit "MFG Default Feature Setup" = X,
        codeunit "MFG MCP Setup" = X,
        codeunit "MFG No. Series Mgt." = X,
        codeunit "MFG Config. Package Mgt." = X,
        table "MFG Preflight Setup" = X,
        table "MFG Preflight Check" = X,
        table "MFG Preflight Finding" = X,
        page "MFG Preflight Setup" = X,
        page "MFG Preflight Checks" = X,
        page "MFG Preflight Findings" = X,
        page "MFG API Preflight Finding" = X,
        page "MFG API Preflight Check" = X,
        page "MFG API Preflight Order" = X,
        page "MFG API Demo Preflight" = X,
        codeunit "MFG Preflight Feature Setup" = X,
        codeunit "MFG Preflight App Area Sub." = X,
        codeunit "MFG Preflight Engine" = X,
        codeunit "MFG Preflight Reactions" = X,
        codeunit "MFG Preflight Locator" = X,
        codeunit "MFG Preflight Events" = X,
        codeunit "MFG Demo Preflight" = X,
        codeunit "MFG Preflight No Check" = X,
        codeunit "MFG Preflight Collector" = X,
        codeunit "MFG Check Routing Link" = X,
        codeunit "MFG Check Flushing Tracking" = X,
        codeunit "MFG Check Missing Bin" = X,
        codeunit "MFG Check Uncertified Design" = X,
        table "MFG WIP Setup" = X,
        table "MFG Finish Check" = X,
        table "MFG Finish Proposal" = X,
        page "MFG WIP Setup" = X,
        page "MFG Finish Checks" = X,
        page "MFG Finish Proposals" = X,
        page "MFG API Finish Proposal" = X,
        page "MFG API Finish Check" = X,
        page "MFG API WIP Order" = X,
        page "MFG API Demo WIP" = X,
        codeunit "MFG WIP Feature Setup" = X,
        codeunit "MFG WIP App Area Sub." = X,
        codeunit "MFG WIP Engine" = X,
        codeunit "MFG WIP Finish Order" = X,
        codeunit "MFG WIP Value Entries" = X,
        codeunit "MFG Demo WIP" = X,
        codeunit "MFG Finish No Check" = X,
        codeunit "MFG WIP Locator" = X,
        codeunit "MFG Check Missing Consumption" = X,
        codeunit "MFG Check Open Whse. Activity" = X,
        codeunit "MFG Check Unfinished Ops." = X,
        table "MFG Refresh Setup" = X,
        table "MFG Refresh Run" = X,
        table "MFG Refresh Comp. Snapshot" = X,
        table "MFG Refresh Oper. Snapshot" = X,
        table "MFG Refresh Change" = X,
        page "MFG Refresh Setup" = X,
        page "MFG Refresh Runs" = X,
        page "MFG Refresh Changes" = X,
        page "MFG API Refresh Run" = X,
        page "MFG API Refresh Change" = X,
        page "MFG API Demo Refresh" = X,
        codeunit "MFG Refresh Feature Setup" = X,
        codeunit "MFG Refresh App Area Sub." = X,
        codeunit "MFG Refresh Engine" = X,
        codeunit "MFG Refresh Reactions" = X,
        codeunit "MFG Refresh Locator" = X,
        codeunit "MFG Refresh Events" = X,
        codeunit "MFG Refresh Session" = X,
        codeunit "MFG Refresh Notification" = X,
        codeunit "MFG Demo Refresh" = X,
        codeunit "MFG Refresh No Object" = X,
        codeunit "MFG Refresh Components" = X,
        codeunit "MFG Refresh Operations" = X;
}
